// Separate learning views, reachable by URL and browser history.
const routes=['positions','rules','preflop','sizing','pot-odds','postflop','practice'];
const durations=[12,15,20,15,20,20,25];
const outcomes=['Находи своё место и понимай, когда твой ход.','Понимай, кто выиграл и что делают кнопки действий.','Читай обозначения карт и выбирай, с чем начать.','Считай ставку и объясняй, зачем её делать.','Сравнивай цену доплаты с шансом выиграть.','Выбирай действие после открытия общих карт.','Пробуй, читай объяснения и повторяй сложное.'];
const icons=['◎','♠','▦','◒','%','↗','◇'];
const originalNavigate=navigate;
const originalQuestion=renderQuestion;
const originalTable=renderTable;
let routeMode=false;
const originalTitle='За столом — школа кэш-покера';
document.querySelector('header').insertAdjacentHTML('beforeend','<nav class="topnav" aria-label="Разделы школы"><a href="#/course">Мой курс</a><a href="#/practice">Тренировка <span>↗</span></a></nav>');
document.querySelector('.brand').href='#/course';
document.body.insertAdjacentHTML('afterbegin','<a class="skip-link" href="#main">Перейти к уроку</a>');
$('#main').setAttribute('tabindex','-1');
function focusMain(){const heading=$('#main h1');if(heading){heading.setAttribute('tabindex','-1');heading.focus({preventScroll:true})}window.scrollTo({top:0,behavior:'instant'})}
function routeFor(i){return '#/'+routes[i]}
navigate=function(i){if(!Number.isInteger(i)||i<0||i>6)return;if(!routeMode&&location.hash!==routeFor(i)){history.pushState(null,'',routeFor(i))}originalNavigate(i);decorateLesson(i);document.title=names[i]+' — За столом'};
function decorateLesson(i){$('#main').classList.toggle('practice-page',i===6);$('#main').classList.remove('course-page');document.querySelectorAll('[data-module]').forEach(b=>b.setAttribute('title',names[Number(b.dataset.module)]));const p=$('#main>.eyebrow');p.innerHTML=`<a href="#/course">МОЙ КУРС</a><span> / </span>БЛОК 0${i+1} <span class="reading-time">${durations[i]} мин</span>`;const lead=$('#main>.lead');lead.insertAdjacentHTML('afterend',`<div class="lesson-objective"><span>ЦЕЛЬ УРОКА</span>${outcomes[i]}</div>`);const interactive=$('#interactive'),article=$('.lesson-copy');if([2,3,4].includes(i)&&article){const shell=document.createElement('div');shell.className='learning-workspace';article.before(shell);shell.append(article,interactive)}if(i===1&&article){const samples=document.createElement('div');samples.className='combination-sample';samples.innerHTML='<div><span class="eyebrow">ПЯТЬ ЛУЧШИХ КАРТ</span><h2>Каждая карта считается.</h2><p>Флеш: одна масть, любые ранги.</p></div><div class="cards">'+cardHTML(['A♥','J♥','8♥','5♥','2♥'])+'</div>';article.before(samples)}if(i===5&&article){article.insertAdjacentHTML('beforebegin','<div class="decision-path"><span>Что у меня?</span><b>→</b><span>Кто против меня?</span><b>→</b><span>Зачем ставить?</span><b>→</b><span>Сколько?</span></div>')} }
function cardHTML(cards){return cards.map(c=>`<span class="card ${/[♥♦]/.test(c)?'red':''}" aria-label="${c}"><span>${c.slice(0,-1)}</span><small>${c.slice(-1)}</small></span>`).join('')}
renderQuestion=function(){originalQuestion();const q=$('#question');if(!q)return;const title=q.querySelector('h2');if(!title)return;const cards=title.textContent.match(/[AKQJT2-9][♠♥♦♣]/g);if(cards){const spot=document.createElement('div');spot.className='spot-visual';spot.innerHTML='<span class="eyebrow">КАРТЫ ИЗ УСЛОВИЯ</span><div class="cards">'+cardHTML(cards)+'</div>';title.after(spot)}const feedback=q.querySelector('.feedback');if(feedback){feedback.insertAdjacentHTML('beforeend','<div class="review-prompt">Объясни своими словами: какой факт в условии определил решение?</div>')} };
renderTable=function(){originalTable();const center=$('.table-center');if(center&&!positionQuiz)center.insertAdjacentHTML('beforeend','<div class="table-mark">♠</div><span class="table-caption">ПОЗИЦИЯ → ИНФОРМАЦИЯ → РЕШЕНИЕ</span>')};
function renderCourse(){moduleId=-1;document.title=originalTitle;$('#main').className='course-page';$('#modules').innerHTML=names.map((n,j)=>`<button data-module="${j}"><span>0${j+1}</span>${n}</button>`).join('');const solved=Object.keys(answers).length;$('#main').innerHTML=`<p class="eyebrow">ТВОЯ ШКОЛА КЭШ-ПОКЕРА</p><div class="course-heading"><h1>Учись видеть<br>больше, чем карты.</h1><div class="course-summary"><strong>14</strong><span>теоретических блоков<br>и практика за столом</span></div></div><p class="lead">Начни с нуля: что означают карты, когда твой ход и зачем ставить фишки. Читай один урок, пробуй пример и переходи к практике. Незнакомые слова можно открыть в словаре.</p><section class="first-steps"><h2>Первый раз в покере? Начни здесь.</h2><p>Тебе дают две карты. До пяти общих карт появятся в центре стола. Игроки по очереди решают, платить фишки или сбросить карты. Победитель забирает поставленные фишки — банк.</p><ol><li><b>Найди своё место.</b> В первом уроке передвигай кнопку D и узнавай, кто ходит.</li><li><b>Разберись с картами и действиями.</b> Во втором уроке есть примеры комбинаций, ставок и BB.</li><li><b>Попробуй без спешки.</b> На сайте выбирай ответы; после них откроется объяснение. Пересдавать можно.</li></ol><p>Все фишки учебные. Прогресс хранится в этом браузере; тренер в чате не получает его автоматически.</p></section><a class="continue-card" href="#/positions"><div><span class="eyebrow">НАЧНИ С ОСНОВ · 12 МИН</span><h2>Сначала найди<br>свою позицию.</h2><span class="continue-button">Открыть первый урок <b>↗</b></span></div><div class="mini-table" aria-hidden="true"><span class="mini-btn">BTN <b>D</b></span><span class="mini-co">CO</span><span class="mini-bb">BB</span><strong>♠</strong><i>6-MAX</i></div></a><div class="section-heading"><h2>Твой маршрут</h2><span>6 базовых уроков · задач: ${quiz.length} · решено: ${solved}</span></div><div class="course-grid">${names.map((n,i)=>`<a class="course-card" href="${routeFor(i)}"><div class="course-card-top"><span class="course-icon">${icons[i]}</span><span>0${i+1} / ${durations[i]} мин</span></div><h3>${n}</h3><p>${outcomes[i]}</p><div class="course-card-bottom"><span>${i===0?'Интерактивный стол':i===2?'169 стартовых рук':i===3||i===4?'Калькулятор + примеры':i===6?'Разбор каждого ответа':'Теория + проверка'}</span><b>↗</b></div></a>`).join('')}</div><div class="study-rhythm"><div class="rhythm-icon">◷</div><div><h3>20–30 минут за одну сессию</h3><p>Изучи один блок, реши задания и объясни ошибки своими словами. Уверенное решение важнее скорости.</p></div><a href="#/practice">К практике →</a></div><footer>Учебный стол на шестерых. В основных примерах у каждого по 100 больших блайндов.<br>Все занятия без реальных денежных ставок. Результаты задач хранятся только в текущей сессии страницы.</footer>`}
function applyRoute(){const r=location.hash.replace('#/','');routeMode=true;const i=routes.indexOf(r);if(i>=0)navigate(i);else renderCourse();routeMode=false;focusMain();document.querySelectorAll('.topnav a').forEach(a=>a.classList.toggle('active',a.hash===location.hash))}
window.addEventListener('hashchange',applyRoute);
window.addEventListener('popstate',applyRoute);
$('.skip-link').addEventListener('click',e=>{e.preventDefault();focusMain()});
applyRoute();
