// Separate learning views, reachable by URL and browser history.
const routes=['positions','rules','preflop','sizing','pot-odds','postflop','practice'];
const durations=[12,15,20,15,20,20,25];
const outcomes=['Определяй позицию от кнопки и порядок действий.','Сравнивай комбинации и понимай действия игроков.','Выбирай стартовую руку с учётом своего места.','Считай открытия, 3-беты и доли банка.','Находи порог колла и не путай шансы дро.','Планируй действия на флопе, тёрне и ривере.','Проверь знания и вернись к своим ошибкам.'];
const icons=['◎','♠','▦','◒','%','↗','◇'];
const originalNavigate=navigate;
const originalQuestion=renderQuestion;
const originalTable=renderTable;
let routeMode=false;
const originalTitle='За столом — школа кэш-покера';
document.querySelector('header').insertAdjacentHTML('beforeend','<nav class="topnav" aria-label="Разделы школы"><a href="#/course">Мой курс</a><a href="#/practice">Тренировка <span>↗</span></a></nav>');
document.querySelector('.brand').href='#/course';
document.body.insertAdjacentHTML('afterbegin','<a class="skip-link" href="#main">Перейти к уроку</a>');
$('#main').setAttribute('tabindex','-1');
function focusMain(){const heading=$('#main h1');if(heading){heading.setAttribute('tabindex','-1');heading.focus({preventScroll:true})}window.scrollTo({top:0,behavior:'instant'})}
function routeFor(i){return '#/'+routes[i]}
navigate=function(i){if(!Number.isInteger(i)||i<0||i>6)return;if(!routeMode&&location.hash!==routeFor(i)){history.pushState(null,'',routeFor(i))}originalNavigate(i);decorateLesson(i);document.title=names[i]+' — За столом'};
function decorateLesson(i){$('#main').classList.toggle('practice-page',i===6);$('#main').classList.remove('course-page');document.querySelectorAll('[data-module]').forEach(b=>b.setAttribute('title',names[Number(b.dataset.module)]));const p=$('#main>.eyebrow');p.innerHTML=`<a href="#/course">МОЙ КУРС</a><span> / </span>БЛОК 0${i+1} <span class="reading-time">${durations[i]} мин</span>`;const lead=$('#main>.lead');lead.insertAdjacentHTML('afterend',`<div class="lesson-objective"><span>ЦЕЛЬ УРОКА</span>${outcomes[i]}</div>`);const interactive=$('#interactive'),article=$('.lesson-copy');if([2,3,4].includes(i)&&article){const shell=document.createElement('div');shell.className='learning-workspace';article.before(shell);shell.append(interactive,article)}if(i===1&&article){const samples=document.createElement('div');samples.className='combination-sample';samples.innerHTML='<div><span class="eyebrow">ПЯТЬ ЛУЧШИХ КАРТ</span><h2>Каждая карта считается.</h2><p>Флеш: одна масть, любые ранги.</p></div><div class="cards">'+cardHTML(['A♥','J♥','8♥','5♥','2♥'])+'</div>';article.before(samples)}if(i===5&&article){article.insertAdjacentHTML('beforebegin','<div class="decision-path"><span>Контекст</span><b>→</b><span>Диапазоны</span><b>→</b><span>Цель</span><b>→</b><span>Размер</span><b>→</b><span>План</span></div>')} }
function cardHTML(cards){return cards.map(c=>`<span class="card ${/[♥♦]/.test(c)?'red':''}" aria-label="${c}"><span>${c.slice(0,-1)}</span><small>${c.slice(-1)}</small></span>`).join('')}
renderQuestion=function(){originalQuestion();const q=$('#question');if(!q)return;const title=q.querySelector('h2');if(!title)return;const cards=title.textContent.match(/[AKQJT2-9][♠♥♦♣]/g);if(cards){const spot=document.createElement('div');spot.className='spot-visual';spot.innerHTML='<span class="eyebrow">КАРТЫ ИЗ УСЛОВИЯ</span><div class="cards">'+cardHTML(cards)+'</div>';title.after(spot)}const feedback=q.querySelector('.feedback');if(feedback){feedback.insertAdjacentHTML('beforeend','<div class="review-prompt">Объясни своими словами: какой факт в условии определил решение?</div>')} };
renderTable=function(){originalTable();const center=$('.table-center');if(center&&!positionQuiz)center.insertAdjacentHTML('beforeend','<div class="table-mark">♠</div><span class="table-caption">ПОЗИЦИЯ → ИНФОРМАЦИЯ → РЕШЕНИЕ</span>')};
function renderCourse(){moduleId=-1;document.title=originalTitle;$('#main').className='course-page';$('#modules').innerHTML=names.map((n,j)=>`<button data-module="${j}"><span>0${j+1}</span>${n}</button>`).join('');const solved=Object.keys(answers).length;$('#main').innerHTML=`<p class="eyebrow">ТВОЯ ШКОЛА КЭШ-ПОКЕРА</p><div class="course-heading"><h1>Учись видеть<br>больше, чем карты.</h1><div class="course-summary"><strong>7</strong><span>блоков от основ<br>до решений за столом</span></div></div><p class="lead">Короткая теория, понятные примеры и практика с разбором. Проходи курс последовательно — от первого блайнда до плана на ривер.</p><a class="continue-card" href="#/positions"><div><span class="eyebrow">НАЧНИ С ОСНОВ · 12 МИН</span><h2>Сначала найди<br>свою позицию.</h2><span class="continue-button">Открыть первый урок <b>↗</b></span></div><div class="mini-table" aria-hidden="true"><span class="mini-btn">BTN <b>D</b></span><span class="mini-co">CO</span><span class="mini-bb">BB</span><strong>♠</strong><i>6-MAX</i></div></a><div class="section-heading"><h2>Твой маршрут</h2><span>6 уроков + ${quiz.length} задания · ${solved} решено</span></div><div class="course-grid">${names.map((n,i)=>`<a class="course-card" href="${routeFor(i)}"><div class="course-card-top"><span class="course-icon">${icons[i]}</span><span>0${i+1} / ${durations[i]} мин</span></div><h3>${n}</h3><p>${outcomes[i]}</p><div class="course-card-bottom"><span>${i===0?'Интерактивный стол':i===2?'169 стартовых рук':i===3||i===4?'Калькулятор + примеры':i===6?'Разбор каждого ответа':'Теория + проверка'}</span><b>↗</b></div></a>`).join('')}</div><div class="study-rhythm"><div class="rhythm-icon">◷</div><div><h3>20–30 минут за одну сессию</h3><p>Изучи один блок, реши задания и объясни ошибки своими словами. Уверенное решение важнее скорости.</p></div><a href="#/practice">К практике →</a></div><footer>Кэш 6-max · 100 BB · без анте. Учебные диапазоны и линии упрощены.<br>Все занятия без реальных денежных ставок. Результаты задач хранятся только в текущей сессии страницы.</footer>`}
function applyRoute(){const r=location.hash.replace('#/','');routeMode=true;const i=routes.indexOf(r);if(i>=0)navigate(i);else renderCourse();routeMode=false;focusMain();document.querySelectorAll('.topnav a').forEach(a=>a.classList.toggle('active',a.hash===location.hash))}
window.addEventListener('hashchange',applyRoute);
window.addEventListener('popstate',applyRoute);
$('.skip-link').addEventListener('click',e=>{e.preventDefault();focusMain()});
applyRoute();
