(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.Poker=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
 'use strict';
 const suits=['♣','♦','♥','♠'],ranks='23456789TJQKA',labels=['Старшая карта','Пара','Две пары','Тройка','Стрит','Флеш','Фулл-хаус','Каре','Стрит-флеш'];
 const value=c=>Math.floor(c/4)+2,suit=c=>c%4,card=c=>ranks[value(c)-2]+suits[suit(c)];
 function parse(text){const a=Array.from(text);const r=ranks.indexOf(a[0]),s=suits.indexOf(a[1]);if(r<0||s<0)throw Error('Неизвестная карта');return r*4+s}
 function rng(seed){let a=seed>>>0;return()=>{a+=0x6D2B79F5;let t=a;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
 function shuffle(random){const d=Array.from({length:52},(_,i)=>i);for(let i=51;i>0;i--){const j=Math.floor(random()*(i+1));[d[i],d[j]]=[d[j],d[i]]}return d}
 function five(cs){const rs=cs.map(value).sort((a,b)=>b-a),counts={};rs.forEach(r=>counts[r]=(counts[r]||0)+1);const groups=Object.entries(counts).map(([r,n])=>[n,+r]).sort((a,b)=>b[0]-a[0]||b[1]-a[1]);const unique=[...new Set(rs)];if(unique.includes(14))unique.push(1);let straight=0;for(let i=0;i<=unique.length-5;i++)if(unique[i]-unique[i+4]===4){straight=unique[i];break}const flush=cs.every(c=>suit(c)===suit(cs[0]));let score;if(straight&&flush)score=[8,straight];else if(groups[0][0]===4)score=[7,groups[0][1],groups[1][1]];else if(groups[0][0]===3&&groups[1][0]===2)score=[6,groups[0][1],groups[1][1]];else if(flush)score=[5,...rs];else if(straight)score=[4,straight];else if(groups[0][0]===3)score=[3,groups[0][1],...groups.slice(1).map(x=>x[1])];else if(groups[0][0]===2&&groups[1][0]===2)score=[2,...groups.slice(0,2).map(x=>x[1]),groups[2][1]];else if(groups[0][0]===2)score=[1,groups[0][1],...groups.slice(1).map(x=>x[1])];else score=[0,...rs];while(score.length<6)score.push(0);return{score,n:score.reduce((a,b)=>a*15+b,0),label:labels[score[0]],best:cs.slice()}}
 function evaluate(cs){if(cs.length<5||cs.length>7||new Set(cs).size!==cs.length||cs.some(c=>!Number.isInteger(c)||c<0||c>51))throw Error('Нужно 5–7 уникальных карт');let best=null;for(let a=0;a<cs.length-4;a++)for(let b=a+1;b<cs.length-3;b++)for(let c=b+1;c<cs.length-2;c++)for(let d=c+1;d<cs.length-1;d++)for(let e=d+1;e<cs.length;e++){const h=five([cs[a],cs[b],cs[c],cs[d],cs[e]]);if(!best||h.n>best.n)best=h}return best}
 const handKey=cs=>{const [a,b]=cs.slice().sort((a,b)=>value(b)-value(a));return ranks[value(a)-2]+ranks[value(b)-2]+(value(a)===value(b)?'':suit(a)===suit(b)?'s':'o')};
 const bb=n=>(n/100).toLocaleString('ru-RU',{maximumFractionDigits:2});
 class Game{
  constructor(options={}){this.seed=options.seed??Math.floor(Math.random()*4294967295);this.random=rng(this.seed);this.deck=shuffle(this.random);this.button=options.button??0;this.hero=options.hero??3;this.street=0;this.board=[];this.log=[];this.done=false;this.rake=0;this.rakeRate=options.rakeRate??0;this.rakeCap=options.rakeCap??300;if(this.rakeRate<0||this.rakeRate>.1||this.rakeCap<0)throw Error('Неверный рейк');this.aggressor=null;const styles=['tight','calling','aggressive','regular','calling','regular'];this.players=Array.from({length:6},(_,i)=>({id:i,name:i===this.hero?'Ты':['Алекс','Ника','Макс','Лев','Мира','Ян'][i],stack:options.stacks?.[i]??(options.stack??100)*100,bet:0,total:0,folded:false,cards:[],actedAt:null,style:options.style&&options.style!=='mixed'?options.style:styles[i],last:''}));if(this.players.some(p=>!Number.isInteger(p.stack)||p.stack<1)||!Number.isInteger(this.button)||this.button<0||this.button>5)throw Error('Неверные параметры стола');this.initial=this.players.map(p=>p.stack);this.initialTotal=this.initial.reduce((a,b)=>a+b,0);for(let round=0;round<2;round++)for(let n=1;n<=6;n++)this.players[(this.button+n)%6].cards.push(this.deck.pop());this.pay((this.button+1)%6,50);this.players[(this.button+1)%6].last='SB 0,5';this.pay((this.button+2)%6,100);this.players[(this.button+2)%6].last='BB 1';this.currentBet=100;this.minRaise=100;this.need=new Set(this.players.filter(p=>p.stack>0).map(p=>p.id));this.actor=this.find((this.button+3)%6);this.progress()}
  get pot(){return this.done?0:this.players.reduce((s,p)=>s+p.total,0)}
  position(i){return['BTN','SB','BB','UTG','HJ','CO'][(i-this.button+6)%6]}
  pay(i,amount){const p=this.players[i],n=Math.min(p.stack,amount);p.stack-=n;p.bet+=n;p.total+=n;return n}
  find(start){for(let n=0;n<6;n++){const i=(start+n)%6,p=this.players[i];if(this.need.has(i)&&!p.folded&&p.stack>0)return i}return null}
  legal(i=this.actor){if(this.done||i!==this.actor||i===null)return null;const p=this.players[i],due=Math.max(0,this.currentBet-p.bet),cap=p.bet+p.stack;const other=this.players.some(q=>q.id!==i&&!q.folded&&q.stack>0);const reopened=p.actedAt===null||this.currentBet-p.actedAt>=this.minRaise;return{fold:true,check:due===0,call:Math.min(p.stack,due),due,minTo:this.currentBet===0?100:this.currentBet+this.minRaise,maxTo:cap,raise:other&&reopened&&cap>this.currentBet}}
  act(kind,to){const legal=this.legal();if(!legal)throw Error('Сейчас нет хода');const i=this.actor,p=this.players[i],oldBet=this.currentBet,potBefore=this.pot;let amount=0;if(kind==='fold'){p.folded=true;p.last='Фолд'}else if(kind==='check'){if(!legal.check)throw Error('Нужно ответить на ставку');p.last='Чек'}else if(kind==='call'){if(!legal.call)throw Error('Нет ставки для колла');amount=this.pay(i,legal.call);p.last=p.stack===0?'Колл · олл-ин':'Колл '+bb(amount)}else if(kind==='raise'){if(!legal.raise||!Number.isInteger(to)||to<=this.currentBet||to>legal.maxTo||(to<legal.minTo&&to!==legal.maxTo))throw Error('Недопустимый размер рейза');amount=this.pay(i,to-p.bet);const increment=to-oldBet;this.currentBet=to;if(to>=legal.minTo){this.minRaise=oldBet===0?to:increment;this.need=new Set(this.players.filter(q=>!q.folded&&q.stack>0&&q.id!==i).map(q=>q.id))}else this.players.forEach(q=>{if(!q.folded&&q.stack>0&&q.id!==i&&q.bet<this.currentBet)this.need.add(q.id)});this.aggressor=i;p.last=(oldBet===0?'Ставка ':'Рейз до ')+bb(to)+(p.stack===0?' · олл-ин':'')}else throw Error('Неизвестное действие');p.actedAt=kind==='check'&&oldBet===0?null:this.currentBet;this.need.delete(i);this.log.push({street:this.street,seat:i,kind,paid:amount,to:p.bet,potBefore,board:this.board.slice()});this.actor=this.find((i+1)%6);this.progress()}
  progress(){if(this.done)return;const alive=this.players.filter(p=>!p.folded);if(alive.length===1){this.settle(false);return}this.need.forEach(i=>{const p=this.players[i];if(p.folded||p.stack===0)this.need.delete(i)});const capable=alive.filter(p=>p.stack>0);if(capable.length===1&&capable[0].bet>=this.currentBet)this.need.delete(capable[0].id);this.actor=this.find(this.actor??(this.button+1)%6);if(this.actor!==null)return;if(this.street===3){this.settle(true);return}if(capable.length<=1){while(this.board.length<5)this.reveal();this.settle(true);return}this.reveal();this.currentBet=0;this.minRaise=100;this.players.forEach(p=>{p.bet=0;p.actedAt=null;p.last=p.folded?'Фолд':p.stack===0?'Олл-ин':''});this.need=new Set(capable.map(p=>p.id));this.actor=this.find((this.button+1)%6)}
  reveal(){this.deck.pop();const n=this.board.length===0?3:1;for(let i=0;i<n;i++)this.board.push(this.deck.pop());this.street=this.board.length===3?1:this.board.length===4?2:3;this.log.push({street:this.street,kind:'deal',board:this.board.slice()})}
  settle(showdown){
   const levels=[...new Set(this.players.map(p=>p.total).filter(n=>n>0))].sort((a,b)=>a-b);let prev=0,charged=0;this.payouts=Array(6).fill(0);this.pots=[];
   for(const level of levels){const contrib=this.players.filter(p=>p.total>=level),eligible=contrib.filter(p=>!p.folded).map(p=>p.id);const amount=(level-prev)*contrib.length;prev=level;
    if(contrib.length===1){this.pots.push({amount,refund:true,winners:[contrib[0].id],rake:0});continue}
    if(!eligible.length)throw Error('В банке нет претендентов');const last=this.pots.at(-1);
    if(last&&!last.refund&&last.eligible.join(',')===eligible.join(','))last.amount+=amount;else this.pots.push({amount,eligible,refund:false});
   }
   for(const pot of this.pots){if(pot.refund){this.payouts[pot.winners[0]]+=pot.amount;continue}
    pot.rake=this.board.length>=3?Math.max(0,Math.min(this.rakeCap-charged,Math.floor(pot.amount*this.rakeRate))):0;charged+=pot.rake;pot.amount-=pot.rake;let winners=pot.eligible.slice();
    if(showdown){const scores=winners.map(id=>({id,h:evaluate([...this.players[id].cards,...this.board])})),best=Math.max(...scores.map(x=>x.h.n));winners=scores.filter(x=>x.h.n===best).map(x=>x.id)}
    winners.sort((a,b)=>(a-this.button+5)%6-(b-this.button+5)%6);const share=Math.floor(pot.amount/winners.length),remainder=pot.amount%winners.length;winners.forEach((id,i)=>this.payouts[id]+=share+(i<remainder?1:0));pot.winners=winners;
   }
   this.rake=charged;this.players.forEach(p=>p.stack+=this.payouts[p.id]);this.showdown=showdown;this.done=true;this.actor=null;this.need.clear();this.net=this.players.map((p,i)=>p.stack-this.initial[i]);
   if(this.players.reduce((s,p)=>s+p.stack,0)+this.rake!==this.initialTotal)throw Error('Нарушен баланс фишек');
  }

  view(i=this.actor??this.hero){const p=this.players[i];return{seat:i,position:this.position(i),cards:p.cards.slice(),board:this.board.slice(),stack:p.stack,bet:p.bet,total:p.total,pot:this.pot,street:this.street,currentBet:this.currentBet,minRaise:this.minRaise,legal:this.legal(i),aggressor:this.aggressor,opponents:this.players.filter(q=>q.id!==i).map(q=>({id:q.id,position:this.position(q.id),stack:q.stack,bet:q.bet,total:q.total,folded:q.folded,style:q.style})),style:p.style}}
 }
 function preflopStrength(cs){const vs=cs.map(value).sort((a,b)=>b-a),[a,b]=vs;if(a===b)return .48+(a-2)*.038;return Math.min(.96,(a+b)/34+(suit(cs[0])===suit(cs[1])?.06:0)-(a-b>4?.10:0)+(a-b===1?.025:0))}
 function draws(cs,board){if(board.length===5)return{flush:false,straight:false};const all=[...cs,...board],suitCounts=[0,0,0,0];all.forEach(c=>suitCounts[suit(c)]++);const flush=cs.some(c=>suitCounts[suit(c)]===4);let straight=false;const vs=new Set(all.map(value));if(vs.has(14))vs.add(1);for(let low=1;low<=10;low++){let n=0;for(let j=low;j<low+5;j++)if(vs.has(j))n++;if(n===4&&cs.some(c=>{const r=value(c)===14&&low===1?1:value(c);return r>=low&&r<low+5&&!board.some(b=>value(b)===value(c))}))straight=true}return{flush,straight:straight&&evaluate(all).score[0]<4}}
 function policy(v,random){const l=v.legal;if(!l)throw Error('Нет хода');const r=random(),tight=v.style==='tight',loose=v.style==='calling',agg=v.style==='aggressive',alive=v.opponents.filter(p=>!p.folded).length;let strength,draw=false;if(v.street===0)strength=preflopStrength(v.cards);else{const h=evaluate([...v.cards,...v.board]);const boardPair=new Set(v.board.map(value)).size<v.board.length;strength=[.15,.45,.65,.8,.88,.91,.96,.99,1][h.score[0]];if(h.score[0]===1&&boardPair&&!v.cards.some(c=>v.board.some(b=>value(b)===value(c))))strength=.23;const d=draws(v.cards,v.board);draw=d.flush||d.straight;if(draw)strength=Math.max(strength,.42)}
  const posBonus=['CO','BTN','SB'].includes(v.position)?.1:0;let raise=false,target=l.minTo;if(v.street===0){const unopened=v.currentBet===100;const threshold=(tight?.74:loose?.59:.67)-posBonus;if(unopened){if(strength<threshold&&!l.check)return{kind:'fold'};raise=strength>threshold&&(r>(loose?.45:.05));target=v.position==='SB'?300:250}else{raise=strength>(agg?.84:.9)&&r>.25;target=Math.max(l.minTo,Math.round(v.currentBet*(v.position==='BTN'?3:4)));const cost=l.call/Math.max(1,v.pot+l.call);if(strength<(tight?.74:loose?.59:.66)||l.call>v.stack*.6&&strength<.87){if(!l.check&&(!loose||cost>.12||r>.3))return{kind:'fold'}}}}
  else{const fraction=l.call/Math.max(1,v.pot+l.call);if(l.call>0){if(strength<(loose?.28:.39)+fraction*.4&&!draw&&r>(agg?.2:.08))return{kind:'fold'};if(alive>2&&strength<.48&&fraction>.17&&!draw&&!loose)return{kind:'fold'};raise=strength>.83&&r>.55||agg&&draw&&r>.80;target=Math.max(l.minTo,Math.round(v.currentBet*3))}else{raise=(strength>.57&&r>(loose?.5:.2))||(draw&&r>(agg?.35:.65))||(agg&&alive===1&&r>.87);target=Math.max(100,Math.round(v.pot*(strength>.8?.75:.45)))}}
  if(raise&&l.raise){target=Math.min(l.maxTo,Math.max(l.minTo,target));return{kind:'raise',to:target}}return l.check?{kind:'check'}:{kind:'call'}
 }
 function coach(v){const l=v.legal,active=v.opponents.filter(p=>!p.folded),effective=Math.min(v.stack,Math.max(0,...active.map(p=>p.stack+p.bet-v.bet))),cap=v.total+(l?.call||0),eligiblePot=cap+v.opponents.reduce((sum,p)=>sum+Math.min(p.total,cap),0),price=l?l.call/(eligiblePot||1):0;const notes=[];notes.push(`Ты на ${v.position}. Соперников осталось: ${active.length}. У тебя ещё ${bb(v.stack)} BB. Против соперника с самым большим стеком можно дополнительно разыграть до ${bb(effective)} BB.`);if(l?.check)notes.push('Сейчас доплачивать не нужно. Чек — передать ход и оставить карты у себя.');if(l?.call)notes.push(`Чтобы остаться в игре, доплати ${bb(l.call)} BB — это колл. Доступный тебе банк после доплаты: ${bb(eligiblePot)} BB. Делим доплату на этот банк: требуется около ${(price*100).toLocaleString('ru-RU',{maximumFractionDigits:1})}% доли выигрыша без комиссии. Это требование цены, а не оценка твоих карт.`);if(l?.call){if(active.some(p=>p.stack===0&&p.total<cap))notes.push('Участвуешь в нескольких банках: в каждом могут быть разные соперники и шансы победить. Фишки чужих банков в цену не включены.');if(v.street<3&&v.stack>l.call&&active.some(p=>p.stack>0))notes.push('Впереди ещё могут попросить фишки. Эта доплата не всегда оплачивает все оставшиеся карты; другой игрок тоже может повысить.')}if(v.street===0){const limped=active.some(p=>p.bet===100&&(p.position!=='BB'));notes.push(v.currentBet>100?'Перед тобой повысили. Посмотри, кто это сделал и насколько. Таблица первого рейза здесь не даёт готового ответа.':v.position==='BB'?'Ты на BB, повышения не было. Если ставки равны, можно чекнуть и увидеть общие карты без доплаты.':limped?'Кто-то уже уравнял большой блайнд — вошёл лимпом. Таблица для случая «все сбросили» здесь не применяется.':'Пока никто не вошёл в игру до тебя. Найди свои две карты в учебной таблице твоей позиции: зелёная клетка — первый рейз, серая — сброс.');notes.push('Ты не обязан доплачивать только потому, что уже поставил блайнд. Оцени, стоит ли рисковать новыми фишками.')}else{const h=evaluate([...v.cards,...v.board]),d=draws(v.cards,v.board);notes.push(`Из своих и общих карт сейчас получается: ${h.label.toLowerCase()}. Часть или вся эта комбинация может лежать на столе и быть доступна сопернику.`);if(d.flush||d.straight)notes.push('Есть шанс собрать флеш или стрит следующей картой — это дро. Посчитай, какие карты помогут. Даже после улучшения соперник иногда остаётся сильнее.');notes.push(active.length>1?'Против тебя несколько игроков. Для победы блефом сбросить должны все. Если руки нет и доплата не нужна, рассмотри чек.':'Перед ставкой назови более слабую руку, которая может заплатить, или более сильную, которую надеешься заставить сбросить.');if(v.street===3)notes.push('Пятая общая карта уже открыта. Новых карт не будет. Для колла важно, достаточно ли часто твоя рука сильнее того, с чем соперник может так ставить.')}return{price,eligiblePot,effective,notes}}
 return{Game,evaluate,five,card,parse,rank:value,suit,handKey,bb,rng,shuffle,policy,coach,draws};
});
