const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {JSDOM}=require('jsdom'),root=require('node:path').resolve(__dirname,'..');
function boot(saved,blocked=false){const d=new JSDOM(fs.readFileSync(root+'/index.html','utf8'),{url:'http://localhost/',runScripts:'outside-only',pretendToBeVisual:true});d.window.scrollTo=()=>{};d.window.confirm=()=>true;if(saved!==undefined)d.window.localStorage.setItem('za-stolom.training.v2',typeof saved==='string'?saved:JSON.stringify(saved));if(blocked){d.window.Storage.prototype.getItem=()=>{throw new d.window.DOMException('blocked','SecurityError')};d.window.Storage.prototype.setItem=()=>{throw new d.window.DOMException('blocked','SecurityError')}}for(const f of ['app.js','course.js','engine.js','advanced.js','drills.js','trainer.js'])vm.runInContext(fs.readFileSync(root+'/'+f,'utf8'),d.getInternalVMContext());return d}
function route(d,r){d.window.location.hash='#/'+r;d.window.dispatchEvent(new d.window.HashChangeEvent('hashchange'))}
function click(d,s){const e=d.window.document.querySelector(s);assert(e,s);e.click()}
function choose(d,s,value){const el=d.window.document.querySelector(s);el.value=value;el.dispatchEvent(new d.window.Event('change',{bubbles:true}))}
test('retry errors keeps the selected error batch instead of switching to all 59 tasks',()=>{const d=boot();route(d,'scenarios');click(d,'[data-answer="1"]');choose(d,'#quiz-filter','Ошибки');click(d,'#retry-topic');assert.equal(d.window.document.querySelector('#quiz-filter').value,'Ошибки');assert.match(d.window.document.querySelector('#question .eyebrow').textContent,/1 \/ 1/);click(d,'[data-answer="0"]');assert.match(d.window.document.querySelector('.feedback').textContent,/Верно/);d.window.close()});
test('corrupted history and noncanonical answer keys cannot break valid progress',()=>{const d=boot({version:2,answers:{'01':0,'2':1},history:[{seed:1,net:0,players:[],log:[],decisions:[],reflection:{bad:true}}]});for(const r of ['course','history','progress','table']){route(d,r);assert(d.window.document.querySelector('main>h1')||d.window.document.querySelector('main h1'))}route(d,'progress');assert.match(d.window.document.querySelector('.progress-metrics').textContent,/1\/59/);assert.match(d.window.document.querySelector('footer').textContent,/повреждённые/);d.window.close()});
test('unavailable storage is reported consistently in basic and advanced routes',()=>{const d=boot(undefined,true);for(const r of ['course','positions','scenarios','table','progress']){route(d,r);assert.match(d.window.document.querySelector('footer').textContent,/недоступно/)}d.window.close()});
test('invalid JSON is recoverable and subsequent answers can be saved',()=>{const d=boot('{broken');route(d,'scenarios');click(d,'[data-answer="0"]');const saved=JSON.parse(d.window.localStorage.getItem('za-stolom.training.v2'));assert.equal(saved.answers[0],0);d.window.close()});
test('all 4 guided lines have valid cards, increasing boards, and correctly nested markup',()=>{const d=boot(),hands=d.window.GuidedHands;for(const h of hands){route(d,'drills/'+h.id);for(let i=0;i<h.steps.length;i++){const doc=d.window.document;assert.equal(doc.querySelector('.review-cards').children.length,2);assert.equal(doc.querySelector('footer').parentElement.tagName,'MAIN');const s=h.steps[i];assert.equal(new Set([...h.hand,...s.board]).size,h.hand.length+s.board.length);if(i)assert.deepEqual(s.board.slice(0,h.steps[i-1].board.length),h.steps[i-1].board);click(d,'[data-drill-answer="'+s.right+'"]');click(d,'#drill-next')}assert.match(d.window.document.querySelector('main').textContent,new RegExp(h.steps.length+' из '+h.steps.length))}d.window.close()});
test('calculator boundaries and known arithmetic produce valid results',()=>{const d=boot();route(d,'pot-odds');const doc=d.window.document;assert.equal(doc.querySelector('#odds-result').textContent,'25.0%');assert.match(doc.querySelector('#ev-result').textContent,/\+1.00/);doc.querySelector('#equity').value='101';doc.querySelector('#equity').dispatchEvent(new d.window.Event('input',{bubbles:true}));assert.match(doc.querySelector('#odds-result').textContent,/Проверь/);assert.equal(doc.querySelector('#ev-result').textContent,'');route(d,'sizing');doc.querySelector('#pot').value='';doc.querySelector('#pot').dispatchEvent(new d.window.Event('input',{bubbles:true}));assert.match(doc.querySelector('#bet-result').textContent,/Проверь/);d.window.close()});
test('raise input cannot silently round a bet with more than two decimal places',()=>{const d=boot();route(d,'table');choose(d,'#sim-position','UTG');click(d,'#sim-start');d.window.document.querySelector('#raise-to').value='3.141';click(d,'[data-act="raise"]');assert.match(d.window.document.querySelector('.input-error').textContent,/0,01 BB/);assert(d.window.document.querySelector('[data-act="call"]'));d.window.close()});
test('keyboard focus stays at the decision after starting a hand and at an invalid input',()=>{const d=boot();route(d,'table');choose(d,'#sim-position','UTG');click(d,'#sim-start');assert.equal(d.window.document.activeElement.dataset.act,'call');d.window.document.querySelector('#raise-to').value='-1';click(d,'[data-act="raise"]');assert.equal(d.window.document.activeElement.id,'raise-to');d.window.close()});
test('top navigation does not leave the previous page marked active',()=>{const d=boot();route(d,'course');assert.equal(d.window.document.querySelector('.topnav [aria-current]').hash,'#/course');route(d,'table');assert.equal(d.window.document.querySelector('.topnav [aria-current]'),null);route(d,'scenarios');assert.equal(d.window.document.querySelector('.topnav [aria-current]').hash,'#/practice');d.window.close()});
