const {test}=require('node:test');const assert=require('node:assert/strict');const P=require('../engine.js');
const cards=s=>s.split(' ').map(P.parse);
test('hand categories, wheel, kicker, best 5 and board ties',()=>{
 const examples=['A♣ K♦ 9♥ 7♠ 3♣','A♣ A♦ K♥ 7♠ 3♣','A♣ A♦ K♥ K♠ 3♣','A♣ A♦ A♥ K♠ 3♣','A♣ 2♦ 3♥ 4♠ 5♣','A♣ J♣ 9♣ 7♣ 3♣','A♣ A♦ A♥ K♠ K♣','A♣ A♦ A♥ A♠ K♣','9♣ T♣ J♣ Q♣ K♣'];
 examples.forEach((s,i)=>assert.equal(P.evaluate(cards(s)).score[0],i));
 assert.equal(P.evaluate(cards(examples[4])).score[1],5);
 assert(P.evaluate(cards('A♠ A♥ Q♣ 7♦ 3♣')).n>P.evaluate(cards('A♣ A♦ J♣ 7♥ 3♦')).n);
 assert.equal(P.evaluate(cards('A♠ K♦ Q♣ J♥ T♠ 2♣ 2♦')).n,P.evaluate(cards('A♠ K♦ Q♣ J♥ T♠ 9♣ 9♦')).n);
 assert.equal(P.evaluate(cards('A♠ A♦ A♣ K♥ K♠ K♣ 2♦')).score[1],14);
});
test('invalid action is atomic, BB retains option, street order',()=>{const g=new P.Game({seed:1,button:0});assert.equal(g.actor,3);const before=JSON.stringify(g);assert.throws(()=>g.act('raise',150));assert.equal(JSON.stringify(g),before);for(let i=0;i<5;i++)g.act('call');assert.equal(g.actor,2);assert.equal(g.legal().check,true);g.act('check');assert.equal(g.street,1);assert.equal(g.actor,1);assert.equal(g.board.length,3)});
test('short raise does not reopen; cumulative short raises can reopen',()=>{const g=new P.Game({seed:2,stacks:[10000,10000,10000,10000,350,450]});g.act('raise',250);g.act('raise',350);g.act('raise',450);g.act('call');g.act('fold');g.act('fold');assert.equal(g.actor,3);assert.equal(g.legal().raise,true);assert.equal(g.legal().minTo,600);const h=new P.Game({seed:2,stacks:[10000,10000,10000,10000,350,10000]});h.act('raise',250);h.act('raise',350);h.act('call');h.act('fold');h.act('fold');h.act('fold');assert.equal(h.actor,3);assert.equal(h.legal().raise,false)});
test('multiple side pots, unmatched return, folded contributions and rake',()=>{const g=new P.Game({seed:4});g.players.forEach((p,i)=>{p.total=[1000,2000,3000,0,0,0][i];p.stack=g.initial[i]-p.total;p.folded=i>2});g.board=cards('2♣ 3♦ 7♥ 9♠ J♣');g.players[0].cards=cards('A♣ A♦');g.players[1].cards=cards('K♣ K♦');g.players[2].cards=cards('Q♣ Q♦');g.street=3;g.rakeRate=.05;g.rakeCap=200;g.settle(true);assert.deepEqual(g.payouts,[2850,1950,1000,0,0,0]);assert.equal(g.rake,200);assert.equal(g.pots.at(-1).refund,true)});
test('bot policies and coach never receive hidden opponent cards',()=>{const g=new P.Game({seed:3});const v=g.view();assert(v.opponents.every(x=>!('cards'in x)));const note=P.coach(v);g.players[0].cards=cards('A♠ A♥');assert.deepEqual(P.coach(g.view()),note)});
test('ordinary folded blinds do not create a false side pot',()=>{const g=new P.Game({seed:8});g.players.forEach((p,i)=>{p.total=[0,50,250,250,0,0][i];p.stack=g.initial[i]-p.total;p.folded=i!==3});g.settle(false);assert.equal(g.pots.length,1);assert.equal(g.pots[0].amount,550);assert.equal(g.payouts[3],550)});
test('odd chip at split pot goes clockwise after the button',()=>{const g=new P.Game({seed:9,button:0});g.players.forEach((p,i)=>{p.total=i<3?101:0;p.stack=g.initial[i]-p.total;p.folded=i!==0&&i!==1});g.board=cards('A♣ K♦ Q♥ J♠ T♣');g.players[0].cards=cards('2♦ 3♦');g.players[1].cards=cards('4♦ 5♦');g.settle(true);assert.equal(g.payouts[1],152);assert.equal(g.payouts[0],151)});
test('800 randomized hands conserve chips, terminate, respect betting and unique cards',()=>{for(let seed=1;seed<=800;seed++){const random=P.rng(seed*177);const g=new P.Game({seed,button:seed%6,stacks:Array.from({length:6},()=>Math.floor(random()*20000)+50),rakeRate:seed%2?.05:0,rakeCap:300});let steps=0;while(!g.done){assert(++steps<250,'hand '+seed);const l=g.legal();assert(l);const x=random();let action;if(x<.10)action={kind:'fold'};else if(x<.48&&l.raise)action={kind:'raise',to:x<.24?l.maxTo:Math.min(l.maxTo,l.minTo+Math.floor(random()*1200))};else action=l.check?{kind:'check'}:{kind:'call'};g.act(action.kind,action.to);assert(g.players.every(p=>p.stack>=0&&p.bet>=0));if(!g.done)assert.equal(g.pot+g.players.reduce((s,p)=>s+p.stack,0),g.initialTotal);assert.equal(new Set([...g.players.flatMap(p=>p.cards),...g.board]).size,12+g.board.length)}assert.equal(g.players.reduce((s,p)=>s+p.stack,0)+g.rake,g.initialTotal);if(g.showdown)assert.equal(g.board.length,5)}});
test('200 heuristic bot games complete without illegal bets',()=>{for(let seed=901;seed<=1100;seed++){const g=new P.Game({seed,stack:seed%2?40:200});let steps=0;while(!g.done){assert(++steps<250);const a=P.policy(g.view(),g.random);g.act(a.kind,a.to)}}});
