const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs');const {JSDOM}=require('jsdom');
const root=require('node:path').resolve(__dirname,'..');
function boot(saved){const html=fs.readFileSync(root+'/index.html','utf8');const d=new JSDOM(html,{url:'http://localhost/',runScripts:'outside-only',pretendToBeVisual:true});d.window.scrollTo=()=>{};d.window.confirm=()=>true;if(saved)d.window.localStorage.setItem('za-stolom.training.v2',saved);for(const f of ['app.js','course.js','engine.js','advanced.js','drills.js','trainer.js'])require('node:vm').runInContext(fs.readFileSync(root+'/'+f,'utf8'),d.getInternalVMContext());return d}
function route(d,r){d.window.location.hash='#/'+r;d.window.dispatchEvent(new d.window.HashChangeEvent('hashchange'))}
function click(d,s){const el=d.window.document.querySelector(s);assert(el,'missing '+s);el.click()}
test('BB explains responses without an opening chart and other positions still show all hands',()=>{const d=boot();route(d,'preflop');const doc=d.window.document;assert.equal(doc.querySelectorAll('[data-range]').length,6);click(d,'[data-range="BB"]');assert.equal(doc.querySelectorAll('[data-hand]').length,0);assert.equal(doc.activeElement.dataset.range,'BB');const text=doc.querySelector('#interactive').textContent;for(const phrase of ['Все сбросили, включая SB','Кто-то уравнял 1 BB','Кто-то повысил ставку','1,5 BB'])assert(text.includes(phrase));assert.equal(doc.querySelector('[data-range="BB"]').getAttribute('aria-pressed'),'true');for(const p of ['UTG','HJ','CO','BTN','SB']){click(d,'[data-range="'+p+'"]');assert.equal(doc.querySelectorAll('[data-hand]').length,169);assert.equal(doc.querySelectorAll('[data-range][aria-pressed="true"]').length,1);click(d,'[data-hand="AA"]');assert(doc.querySelector('#hand-detail').textContent.includes('рейз до '+(p==='SB'?'3':'2,5')+' BB'))}d.window.close()});
test('all sections render, all quizzes valid and advanced topics filter',()=>{const d=boot();for(const r of ['course','positions','rules','preflop','sizing','pot-odds','postflop','practice','advanced','advanced/blinds','table','progress','history','scenarios','drills','drills/top-pair']){route(d,r);assert(d.window.document.querySelector('h1'));assert(!d.window.document.body.textContent.includes('undefined'))}route(d,'scenarios');const s=d.window.document.querySelector('#quiz-filter');assert([...s.options].some(x=>x.value==='3-беты'));s.value='3-беты';s.dispatchEvent(new d.window.Event('change',{bubbles:true}));assert(d.window.document.querySelector('#question').textContent.includes('Сквиз')||d.window.document.querySelector('#question').textContent.includes('переповышение'));d.window.close()});
test('full hands play to completion, review and reflection persist',()=>{const d=boot();route(d,'table');click(d,'#sim-start');let count=0;while(d.window.document.querySelector('[data-act]')){assert(++count<50);const doc=d.window.document;if(doc.querySelector('[data-act="check"]'))click(d,'[data-act="check"]');else click(d,'[data-act="call"]')}assert(d.window.document.querySelector('.hand-result'));route(d,'history');const t=d.window.document.querySelector('#reflection');assert(t);t.value='Я сравнил диапазон соперника с ценой колла и проверю решение на ривере.';click(d,'#save-reflection');const saved=d.window.localStorage.getItem('za-stolom.training.v2');assert.equal(JSON.parse(saved).history.length,1);d.window.close();const e=boot(saved);route(e,'history');assert(e.window.document.querySelector('#reflection').value.includes('диапазон'));e.window.close()});
test('quiz attempts, retry and reload preserve meaningful progress',()=>{const d=boot();route(d,'scenarios');click(d,'[data-answer="1"]');let saved=JSON.parse(d.window.localStorage.getItem('za-stolom.training.v2'));assert.equal(saved.answers[0],1);assert.equal(saved.attempts[0].count,1);click(d,'#retry-question');click(d,'[data-answer="0"]');saved=JSON.parse(d.window.localStorage.getItem('za-stolom.training.v2'));assert.equal(saved.attempts[0].correct,1);assert.equal(saved.attempts[0].count,2);const e=boot(JSON.stringify(saved));route(e,'progress');assert(e.window.document.body.textContent.includes('1/'));d.window.close();e.window.close()});
test('invalid raise keeps hand intact and displays feedback; settings apply next hand',()=>{const d=boot();route(d,'table');const sel=d.window.document.querySelector('#sim-position');sel.value='UTG';sel.dispatchEvent(new d.window.Event('change',{bubbles:true}));click(d,'#sim-start');const field=d.window.document.querySelector('#raise-to');assert(field);field.value='-2';click(d,'[data-act="raise"]');assert(d.window.document.querySelector('.input-error').textContent.length>0);assert(d.window.document.querySelector('[data-act="call"]'));d.window.close()});
test('guided hand requires answers, follows explicit teaching line and persists completion',()=>{const d=boot();route(d,'drills/top-pair');for(let i=0;i<4;i++){assert.equal(d.window.document.querySelector('#drill-next'),null);click(d,'[data-drill-answer="0"]');assert(d.window.document.querySelector('.feedback').textContent.includes('Продолжение по учебной линии'));click(d,'#drill-next')}assert(d.window.document.querySelector('#main').textContent.includes('4 из 4'));const saved=JSON.parse(d.window.localStorage.getItem('za-stolom.training.v2'));assert.equal(saved.drills['top-pair'].length,4);d.window.close()});
